name: login_app
description: "Flutter Login page"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  mobx_widget: ^0.5.1
  flutter_modular: ^6.3.4
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: ^0.13.6
  provider: ^6.1.1
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.1
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
